spring.datasource.url=jdbc:mysql://mysql:3306/roomsdekho?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Kittu@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

aws.region=ap-south-1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

